### ISSUE TITLE
VS Code doesn't connect to nREPL

### ISSUE THREAD

**Issue by caiorcferreira** [PEZ/clojure4vscode#10]
I'm having a problem to use the extension. I'm using the following workflow:
1. Start a nREPL with `lein repl` or `lein repl :headless`.
2. Open VS Code
3. Waiting to connect

But the only message that shows is **nrepl - trying to connect**, and when I gave the command for evaluate the form it doesn't respond.
My environment is Ubuntu 16.04 with leningen.

I'm lost in how to proceed, maybe I'm using it in the wrong way, any help is welcome.

Thanks

**Comment by PEZ** [comment]
Hmmm. Do you see a `.nrepl-port` file in the directory where you start the REPL and VS Code from?

Also, what happens if you do a ”manual” connect from VS Code (`ctrl+alt+v c`)?

**Comment by ajmichaels** [comment]
I have the same issue on mac 10.11.6.  It gets stuck trying to connect.  Manually connecting and using a `.nrepl-port` file doesn't seem to help

**Comment by PEZ** [comment]
The connection code is a bit messed up, so there is lots of room for bugs. If you can help me debug this, that would be awesome. It is very easy to run the extension in development mode. Just clone it. Run `npm install`. Open the project in code: `code .`. Put breakpoints in the `connector.js` file. Run the extension: `F5`. Open the Leiningen project directory. See if you hit the breakpoint.

**Comment by ajmichaels** [comment]
@PEZ Not sure if you're addressing me, but I posted a comment briefly because I thought that I had the same issue, but realized I was just being dumb - didn't realize I needed to connect to a running repl.  It works fine for me.

**Comment by PEZ** [comment]
Closing this now. Please reopen if it is still a problem.
