### ISSUE TITLE
Trying to locate Joker even when linting is disabled

### ISSUE THREAD

**Issue by pedrorgirardi** [PEZ/clojure4vscode#11]
Hi, there!

**Calva** is trying to locate **Joker** on my path even when _linting_ is disabled. Is this the expected behavior?

![screen shot 2018-04-18 at 7 34 06 pm](https://user-images.githubusercontent.com/585191/38932216-c1b9f3ce-433f-11e8-8464-92fdb3f1d60d.png)

*Many thanks for making this extension. This is so good for JavaScript programmers coming to ClojureScript. Super nice!

**Comment by PEZ** [comment]
No, that should not be happening. Thanks for the heads-up. And thanks for the praise! Makes me happy!

**Comment by PEZ** [comment]
Should now be fixed. Please let me know if it is or not.

**Comment by pedrorgirardi** [comment]
Yes, it's fixed 🎉

Thank you!
