### ISSUE TITLE
Pasted code doesn't indent correctly

### ISSUE THREAD

**Issue by tjbrandt** [PEZ/clojure4vscode#15]
Keep up the great work, Peter! I noticed a few format-as-you-go issues as I've been using the extension for a while, but most of it is working nicely.

Here's one, and I might file a couple more when I get around to it.

Take the following code snippet:
```
(ns testapp.core
  (:require
   [clojure.string :as string]))
```

If you want to add paste in `[clojure.set :as set]` in as a new required namespace, do the following:

1. Copy the text `[clojure.set :as set]`
2. Put your cursor after `string]` and hit `ENTER`, which correctly lines up your cursor with the first `[`
3. Paste `[clojure.set :as set]`

The auto-indentation indents the new code an extra space:
```
(ns testapp.core
  (:require
   [clojure.string :as string]
    [clojure.set :as set]))
```

An example with slightly different behavior. Start with this:
```
(let [var1 :test]
  (do-something))
```

1. Copy the text `var1 :test`
2. Put your cursor after `:test` to add a new binding to the binding list and hit `ENTER`, which correctly aligns your cursor under `var1`
3. Paste the text.

The pasted text this time gets un-indented in a strange way:
```
(let [var1 :test
  var1 :test]
  (do-something))
```

**Comment by pedrorgirardi** [comment]
Hi @tjbrandt, it will be fixed in the next release. Thank you for reporting this!

The issue was the `"editor.formatOnPaste": false` configuration, so we changed that to default to `true` and that fixes your problem.

**Comment by tjbrandt** [comment]
Thanks, Pedro! Glad it was an easy fix. I set that config manually and it does indeed fix the issue. Appreciate the hard work and the prompt response :)

**Comment by tjbrandt** [comment]
Hey @pedrorgirardi ! It seems like this behavior has regressed slightly.

Start with this:
```
(let [var1 :test]
  (do-something))
```

Then copy this snippet:
```
(let [var2 :test2]
  (do-something-else))
```

And paste it on the line below the original `(do-something)`. You get this:
```
(let [var1 :test]
  (do-something)
  (let [var2 :test2]
  (do-something-else)))
```

The `(do-something-else)` isn't preserving its original indentation anymore. I noticed this issue creep up again a few weeks ago, so I'm wondering if a vscode update somehow changed the behavior. Any tips would be appreciated!

**Comment by PEZ** [comment]
This works OK for me. Are you sure you still have `formatOnPaste` active?

**Comment by tjbrandt** [comment]
Hmm, interesting. So yours indents that last line to a third level, like this?
```
(let [var1 :test]
  (do-something)
  (let [var2 :test2]
    (do-something-else)))
```

Yeah `formatOnPaste` is still set to true. Ok, well maybe I'll sift through my settings more to see if I can find anything when I get a chance. Thanks!

**Comment by PEZ** [comment]
Yeah, it is indented like that when I paste. I'm thinking if it could be a performance issue. I have noticed that formatOnSave sometimes fails and wonder if VSCode might have some timeout for these operations that Calva Format fails to meet.
