### ISSUE TITLE
Fix indentation for following forms: deftest, testing, defn-

### ISSUE THREAD

**Issue by tjbrandt** [PEZ/clojure4vscode#19]
`deftest`, `testing`, and `defn-` should be added to the `oneIndentForms` array in `ontype_formatter.js`.

`deftest` and `testing` should have the form:
```
(deftest my-test
  (testing "some subtest description"
    (test-functions-here)))
```
But auto-indent is doing this:
```
(deftest my-test
         (testing "some subtest description"
                  (test-functions-here)))
```

Similarly, defining a function with `defn-` should behave the same as `defn` with regards to indentation. Should look like this:
```
(defn- private-fn [arg]
  (indents-two-spaces))
```
Actual behavior:
```
(defn- private-fn [arg]
       (this-is-indented-to-far))
```

This is one I could have fixed myself, but I haven't yet gotten ramped up on how to build and test an extension locally :)

**Comment by PEZ** [comment]
Thanks! I have been wondering about what more `oneIndentForms` should be included.

Microsoft has made it super duper easy to work on extensions, btw. With Calva all you need to do is:

1. Run `npm install` in the clone of your fork.
2. Open the project in Code.
3. Run the extension in the Extension Host (go to the Debug view and click the run button, or just press `F5`).

The Extension Host will shadow any installed Calva extension, so no need to disable that.

We should probably add something about how easy it is to contribute in the README.

Let me know if you will have the time to submit this PR, or I will just go ahead and fix this issue tonight (Swedish time).

Note 1: `npm install` will probably touch `package-lock.json` and possibly `package.json` as well. I don't know if we should have `package-lock.json` in git, but for now it is. Just commit the changes.

Note 2: No need to bump the version in `package.json`. The extension publishing tool will take care of that.

**Comment by PEZ** [comment]
Question. Do people have their own macros that should possibly be one-indented? If so we should consider adding a setting for that. Separate issue if so, just asking here.

**Comment by tjbrandt** [comment]
Thanks for the instructions. I'll try to fix it today. Unsure about your macros question--I've only written one or two.

**Comment by PEZ** [comment]
I have never quite figured the numbering out. 😃 

Thanks for the PR!

**Comment by tjbrandt** [comment]
Hey @PEZ,

I'm having trouble running the extension now locally since the shadow-cljs version bump and merge that happened on 5/1.

Now I'm getting:
```
Activating extension 'cospaia.clojure4vscode' failed: Cannot find module 'clojure4vscode/dist/calva.js'.
```
reported as an error by VSCode when I go to Launch my extension via the debug console.

Did you have to do anything to get your local up and running after that? I definitely don't have the file referenced above in my repo.

**Comment by pedrorgirardi** [comment]
Hi @tjbrandt. We've started migrating Calva to ClojureScript so we had to make a few changes so `/dist/calva.js` is now compiled by Shadow CLJS.

You run run `Shift+Cmd+b` - or **Tasks**, **Run Build Task...** to compile Calva and generate the `/dist/calva.js` file. The task will open a terminal and you can see what's going on with the build, once it's finished you can then run the extension with `F5`.

If that doesn't work for you, me please let us know.

**Comment by tjbrandt** [comment]
Thanks, @pedrorgirardi. The build task isn't working in vscode itself, but works just fine when I run `npm run watch` in an outside terminal and allowed me to test my changes. Good enough for me :) I might just have to restart vscode but in the middle of other work.

**Comment by pedrorgirardi** [comment]
Great, @tjbrandt! But funny that the build task did not work for you. 🤔

I saw your PR, thank you for helping to improve Calva!! I'm sure Peter will take a look at it as soon as he can.

**Comment by tjbrandt** [comment]
Ha, me and my tiny PR’s :) You’re welcome. You guys are doing the heavy lifting, so thank _you_!
