### ISSUE TITLE
Calva in CLJS

### ISSUE THREAD

**Issue by pedrorgirardi** [PEZ/clojure4vscode#23]
We don't want to throw all the existing JavaScript code away, that's not very practical. So let's try to incrementally 'migrate' existing functionalities to ClojureScript. But...where should we start? 🤔

**Comment by PEZ** [comment]
At least `message.js` can probably be migrated w/o messing with anything else. Could be a start just to get the infrastructure tested.

**Comment by pedrorgirardi** [comment]
Okay, so `message.js` it is.

**Comment by pedrorgirardi** [comment]
@PEZ did the whole work and it's on the branch `wip-cljs-toolchain`. All seems to be working fine, but we probably need to test more. 
After testing and if it's all fine, we should then merge the changes to `master` and that will be our first step towards migrating **Calva** to ClojureScript.

Thank you @PEZ !

**Comment by pedrorgirardi** [comment]
`message.cljs` is done! It's working well and it was merged into `master`.
