### ISSUE TITLE
BUG: vscode displaying literal ansi color code on windows

### ISSUE THREAD

**Issue by sloxy** [PEZ/clojure4vscode#29]
Bug report coming from conversation in #vscode in clojurians slack on April 28/29/30.

When evaluating code in VSCode, ansi color codes are printed in terminal.

For example, instead of just outputting `nil`, it will output `?[36mnil?[0m`
![vscode-nrel-ansi-codes-in-terminal-output](https://user-images.githubusercontent.com/1625363/39490875-3a919292-4d82-11e8-8987-14d2f0d1a806.png)

In other (Windows) clients which use lein repl which support color output in terminal, the response text would be colorized correctly(with the ansi color information then removed after use).
Noticable, issue seems to be fundamental to Windows as cmd.exe, Powershell & VSCode terminal all suffer from this issue,

![image](https://user-images.githubusercontent.com/36491088/39492847-ca73140c-4d88-11e8-9c7c-e82722ccfa2a.png)

##Other Info
similar to https://github.com/clojure-emacs/cider/pull/275 which was solved client side.

**Comment by pedrorgirardi** [comment]
Thanks for taking the time to report, @sloxy . We will see what we can do. :)

**Comment by sloxy** [comment]
using rebel-readline & the instructions from https://github.com/clojure/tools.nrepl/blob/master/README.md, this is what the nrepl server responds with:

![image](https://user-images.githubusercontent.com/36491088/39521938-860195de-4e08-11e8-8a0b-a51d6971f81f.png)

**Comment by sloxy** [comment]
cider-nrepl uses puget.printer (cider-nrepl\src\cider\nrepl\middleware\pprint.clj:35) and it doesn't override the default value of print-color which is set to false (puget/printer.clj:99): `:print-color false`
but this isn't adding the ansi code to the return value either:

![image](https://user-images.githubusercontent.com/36491088/39522063-03e59054-4e09-11e8-83ea-0eac35e36734.png)

**Comment by PEZ** [comment]
This could be related: https://github.com/Microsoft/vscode/issues/45693

**Comment by sloxy** [comment]
found issue.
i had `:plugins [[venantius/ultra "0.5.2"]]` in my leiningen profile..

removing that resolved issue:
![image](https://user-images.githubusercontent.com/36491088/39579181-0238af7c-4ede-11e8-9f80-19ba1c4202c3.png)
