### ISSUE TITLE
Requires with `:refer :all` cause unresolved symbols and unused namespace errors

### ISSUE THREAD

**Issue by chris** [PEZ/clojure4vscode#30]
I'm finding that if I use `:refer :all` in a namespace require, that Calva shows me some unexpected errors around unresolved symbols and unused namespace. For example, if I have:

```
(ns my.thing.user-test
  (:require [clojure.test :refer :all]))
```

Then assuming I have some tests defined, I will get the following errors:

```
Parse error: Unable to resolve symbol: deftest
Parse error: Unable to resolve symbol: is
Parse warning: unused namespace clojure.test
```

If I change my requires to use `:as`, or to list the referred items (e.g. `[clojure.test :refer [deftest is testing use-fixtures]]`), then the errors go away. I'm relatively new to Clojure, but these tests run fine, so it seems like a Calva parsing issue?  

My environment:

- MacOS
- Calva 1.3.16
- Joker 0.9.1
- Clojure 1.9.0
- Leiningen 2.8.1
- cider/cider-nrepl 0.16.0
- org.clojure/tools.nrepl 0.2.12

**Comment by pedrorgirardi** [comment]
Hi @chris. I'm not familiar with **Joker** so I don't know if there is a workaround for that. If you use `:refer [deftest]` Joker doesn't complain about `deftest` nor about the unused namespace.

**Comment by pedrorgirardi** [comment]
Yep, Joker can't resolve the symbols when using `:refer :all`. 😕 Check this issue: https://github.com/candid82/joker/issues/52

**Comment by chris** [comment]
Thanks @pedrorgirardi , ya per what I mentioned in there, it wasn't a problem if I directly refer the used functions, etc. so, not a big deal, but just wanted to mention it. I guess this is really a Joker issue instead of Calva. I can file it with them.

**Comment by PEZ** [comment]
Thanks for letting us know, @chris. We maybe should add some note in the Calva README about it. Opening this issue again and we can close it when we have either added a note or decided against it.

**Comment by kwladyka** [comment]
IMO it is joker issue and should be discuss in joker issues github, not here. Unless we consider to change joker to something else. I guess not.

It is clearly said Calva use Joker to check it.

Besides of that we can have paragraph in readme:
# Known dependency issue
## Joker
- 2018-05-04, ver. X.Y.Z
`:refer :all` throw warnings https://github.com/PEZ/clojure4vscode/issues/30

**Comment by chris** [comment]
You could add something to the README to state that linter errors are from Joker, but really this was my fault for filing it here - I should have realized it was in Joker and looked there first. Other people may run into this too, and it's always a challenge when you have dependencies, so I think it's also fine to just know that if something like this comes up, it can be redirected to the dependency (Joker, etc.).
