### ISSUE TITLE
[feature] highlight syntax in REPL

### ISSUE THREAD

**Issue by kwladyka** [PEZ/clojure4vscode#32]
Again i will compare it to Cursive.

<img width="817" alt="screen shot 2018-05-04 at 09 25 20" src="https://user-images.githubusercontent.com/3903726/39616712-1bae8810-4f7d-11e8-9661-179063fee4fb.png">

First part is input, next is output. On the bottom I pressed arrow up to display last input to show it work even during writing in REPL.

**Comment by PEZ** [comment]
Yeah, that is wonderful. Unfortunately VS Code does not allow for extensions to build a GUI like that. We have to make do with the built in terminal, which is pretty lame in comparison.

**Comment by kwladyka** [comment]
Do you know right place where we can suggest this as a feature in VS Code? This example of solution is good to show it has value.

**Comment by RicSwirrl** [comment]
This plugin gets you some of the way there: https://github.com/venantius/ultra

**Comment by PEZ** [comment]
@RicSwirrl have you tried using the plugin together with Calva? It seems it should work, and I will try it, but have limited time right now.

**Comment by kwladyka** [comment]
What about `clj` and `deps.edn`?

**Comment by RicSwirrl** [comment]
@PEZ it works inside the vscode terminal

**Comment by PEZ** [comment]
@RicSwirrl, now I got around to testing it out. It is pretty neat!

@kwladyka, this would only help someone using Leiningen.

**Comment by feelextra** [comment]
With the New REPL Window, isn't this feature basically implemented now?

Looking at [PEZ replying to #141](https://github.com/BetterThanTomorrow/calva/issues/141#issuecomment-471220683)

Here's what it looks like right now:
![calva-repl-window](https://user-images.githubusercontent.com/43674238/54920372-be73b780-4f0b-11e9-9a8c-39781aec5e9b.png)
