### ISSUE TITLE
Command to re-run previous(ly failing) tests

### ISSUE THREAD

**Issue by PEZ** [PEZ/clojure4vscode#6]
Rerunning previously failed tests would be nice. As requested in the latest review here: https://marketplace.visualstudio.com/items?itemName=cospaia.clojure4vscode#review-details

**Comment by Bigsy** [comment]
Many thanks for this, I'll give it a test and let you know. Cheers

**Comment by PEZ** [comment]
@Bigsy: I found that running tests were a bit confusing because sometimes the document was not re-evaluated and you would get test results from something that didn't reflect what was showing in the document. I have just released a new version of Calva that should fix this. To me it seems to make the re-running of tests much more useful.
